version: '3.7'

networks:
  hydrodynamic-network:
    name: hydrodynamic-network

services:
  hydrodynamic-service:
    container_name: hydrodynamic-service
    image: hydrodynamic-service
    build:
      context: .
      dockerfile: hydrodynamic-service/Dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - hydrodynamic-logs:/hydrodynamic-service/logs
      - hydrodynamic-2dmodel-input:/hydrodynamic-service/2d-model/input
      - hydrodynamic-2dmodel-output:/hydrodynamic-service/2d-model/output
    ports:
      - 30330:80
    networks:
      - hydrodynamic-network
    restart: always

volumes:
  hydrodynamic-logs:
    name: hydrodynamic-logs
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./volumes/logs
  hydrodynamic-2dmodel-input:
    name: hydrodynamic-2dmodel-input
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./volumes/2d-model/input
  hydrodynamic-2dmodel-output:
    name: hydrodynamic-2dmodel-output
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./volumes/2d-model/output
